### ISSUE TITLE
Änderung des Datentyps von CharField in Textfield

### ISSUE THREAD

**Issue by BastianKrones** [GeoMatDigital/django-geomat#10]
Das [Kommentarfeld](https://github.com/GeoMatDigital/django-geomat/blob/master/geomat/stein/models.py#L179-L183) ist aktuell ein CharField und soll zu einem TextField umgewandelt werden

**Comment by mimischi** [comment]
Eventuell sollte dieses auch im Code von `other` zu `comment` umbenannt werden?

**Comment by BastianKrones** [comment]
Beides erledigt.
