### ISSUE TITLE
Änderung der Strichfarbe und Normalfarbe

### ISSUE THREAD

**Issue by BastianKrones** [GeoMatDigital/django-geomat#11]
[Strichfarbe und Normalfarbe](https://github.com/GeoMatDigital/django-geomat/blob/master/geomat/stein/models.py#L108=L114) bräuchten Optimalerweise auch eine Auswahl aus Farbmöglichkeiten, damit das in Zukunft sortierbar ist. Aktuell ist beides jeweils mit einem CharField realisiert.

**Comment by sheepyhollow** [comment]
Hat sich auch geklärt, oder? Ebenso wie evtl. die anderen issues?

**Comment by mimischi** [comment]
Nein, ist immer noch nicht implementiert im Backend.

**Comment by mimischi** [comment]
Um das mal in Fahrt zu bringen: @sheepyhollow Gibt es eine List an _möglichen_ Farben mit denen die Mineralstücke definiert werden können oder ist das praktisch das gesamte Farbspektrum?

**Comment by chgad** [comment]
Das hat sich fürs erste erledigt.
