### ISSUE TITLE
Hinzufügen eines WYSIWIG-Editors 

### ISSUE THREAD

**Issue by BastianKrones** [GeoMatDigital/django-geomat#12]
Für das Feld [Chemismus](https://github.com/GeoMatDigital/django-geomat/blob/master/geomat/stein/models.py#L175-L178) wäre eine Art WYSIWYG-Editor oder zumindest eine Live-Vorschau der LaTeX Syntax mit Hilfe von MathJax (o. ä.) wünschenswert.

**Comment by mimischi** [comment]
Das Paket scheint nützlich zu sein: [django-ckeditor](https://github.com/django-ckeditor/django-ckeditor). Dazu gibt es noch das [MathJax-Addon](http://ckeditor.com/addon/mathjax).

**Comment by mimischi** [comment]
Gerade folgendes Python Paket entdeckt: [django-mathfield](https://github.com/jongoodnow/django-mathfield)
Allerdings wirbt es nur mit Python 2.7 und Django 1.7 Kompatibilität und wurde zuletzt 2014 aktualisiert. Ich schaue mal, ob es noch geht und eventuell kann man das Ganze ja aktualisieren. Laut README hat es zumindest die Funktionalität die man sich wünscht mit dem Live-Preview im Admin-Bereich.

**Comment by sheepyhollow** [comment]
Können wir das eigentlich schließen? Hat sich doch im GeoMat-Kontext weitgehend erledigt, da keine jax-Formeln eingesetzt werden?

**Comment by BastianKrones** [comment]
Ja, es wird mit reinem HTML/CSS umgesetzt

**Comment by mimischi** [comment]
> Können wir das eigentlich schließen?

Nein, weil es im Backend immer noch per Hand eingegeben wird.

![2017-10-19-090654_539x67_scrot](https://user-images.githubusercontent.com/1052860/31758251-f2060b52-b4ac-11e7-9610-080c38638fb5.png)

Das ist weiterhin das gängige, LaTeX-ähnliche Format. Wie es im Front-End dargestellt wird ist total Wuppe, da die Eingabe für die im Backend arbeitende Person weiterhin erschwert bleibt.

**Comment by chgad** [comment]
Diese Feature hätte man einbauen sollen **bevor** die Eingaben gemacht wurden. @mimischi  du hast recht, es könnte geändert werden **aber** zum jetztigen Zeitpunkt sehe ich nicht mehr den nutzen da keine (?) Minerale mehr hinzu kommen. Stimme als weitestgehend @sheepyhollow  zu  (front end einbindung spielt dennoch keine Rolle). 
Wir hatten uns beim letzten Treffen übrigens auf Englisch als Sprache für Github geeinigt, small reminder.

**Comment by mimischi** [comment]
So what if the data needs to be changed in the future? I don't think closing the issue is a good idea. We should leave it open and mark is as `low priority`.
