### ISSUE TITLE
'display_name' entfernen

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/django-geomat#213]
So weit ich das sehe wird display_name nicht mehr gebraucht und kann daher raus.

**Comment by sheepyhollow** [comment]
Ähm... ich bin verwirrt... Ich dachte, wir hätten uns dann doch auf eine frontendseitige Lösung geeinigt?

**Comment by chgad** [comment]
Hier erledigt 6484f2bf75af5a1eee7d283416cbbe634e2479d4
