### ISSUE TITLE
Bilderliste in profiles vereinfachen

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/django-geomat#214]
Aktuell werden Links zu allen Größen in der Abfrage mitgeliefert.
Da diese generisch sind könnten sie auch im Frontend zusammengesetzt werden, um den overhead zu vermeiden. 

Müsste dann auch entsprechend dokumentiert werden.

**Comment by chgad** [comment]
Overhead? Naja das ist nicht so tragisch.

**Comment by mimischi** [comment]
Ich glaube das ist tatsächlich nur ein Tropfen auf dem heißen Stein.

Außerdem könnten sich die Pfade ändern und dann müsste die Frontend-App zeitgleich mit dem Backend angepasst werden.
So kriegt das Frontend ein Objekt und nutzt den `key` um an den jeweilige `value` zu kommen. Solange der `key` gleich bleibt, ist dem Frontend der `value` Wert egal.

**Comment by sheepyhollow** [comment]
also schließen?

**Comment by chgad** [comment]
Wenn man es vereinfcht machen wir quasi folgendes : 

Das Backend muss die entnommenen url's kürzen, verschickt dann die gekürzten, damit das Frontend sie wieder zusammen setzt. 

Das sind unnötige Bearbeitungsschritte. Zumal ich @mimischi zustimme. Soviel macht das auch nicht aus an payload.

**Comment by sheepyhollow** [comment]
Dann schließen wir das.
