### ISSUE TITLE
Glossareinträge nicht alphabetisch sortiert

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/django-geomat#221]
Die API spuckt die Glossareinträge (offenbar) nicht nach alphabetischer Sortierung der id aus, sondern in gering abweichender Reihenfolge (so stehen z.B. die "Foide" am Ende der Liste und nicht unter `F`).

Ich würde generell einen alphabetischen Output erwarten - davon unabhängig, ob man auch im Frontend sortieren könnte oder nicht.

**Comment by chgad** [comment]
Hier erledigt a8b6e34d6ad6e18e74f78e2505f05361aee65037 .
