### ISSUE TITLE
Maybe remove ChoiceArrayField

### ISSUE THREAD

**Issue by chgad** [GeoMatDigital/django-geomat#276]
See here : 
https://github.com/GeoMatDigital/django-geomat/blob/develop/geomat/stein/models.py#L100

**Comment by mimischi** [comment]
Warum? Das wurde ursprünglich eingeführt, weil einige Handstücke mehrere Angaben für Bruch, etc. brauchten. Siehe: https://github.com/GeoMatDigital/django-geomat/commit/6e9fa3991d10c9f113988fbeb3aaf308b4c14568

**Comment by chgad** [comment]
Ah ich erinnere mich. Ich werde das nochmal überprüfen ob es tatsächlich genutzt wird.
