### ISSUE TITLE
Steckbrief-Thumbnails ins Backend

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/django-geomat#296]
Für die Thumbnails der Steckbriefe gab es in der dynamischen Version noch keine richtig saubere Lösung, die unabhängig vom Frontend ist. 
Diese Thumbnails sollten in der DB liegen und der `/profiles` Endpoint sollte die passenden URLs je Layer mitliefern, zusammen mit dem `link`.

**Comment by sheepyhollow** [comment]
Da war mal etwas mit dem Namen und den ersten 4 Buchstaben gedacht. Das ist aber unsauber.

**Comment by mkay-sh** [comment]
Hier mal eine Zusammenfassung unserer Diskussion von heute:
1. Anpassung vom `profiles`-Endpoint. Es sollte immer der gesamte Baum der Steckbriefe zurückgegeben werden.
2. Metadaten für die Kategorien mit zurückgeben. Zusätzlich zum Link sollte ein Pfad zum Thumbnail und der Kommentar übergeben werden.
3. Sprachproblem: Der Key einer Kategorie sollte nicht übersetzt werden, egal in welcher Sprache der User anfragt. Falls man eine übersetzte Version zurückgeben möchte, sollte diese in einem seperaten Feld landen.

Beispiel für Links:
```json
{
  "KEY (z.B. Elements)": {
    "thumbnail": "Pfad zum Thumbnail im CDN",
    "comment": "OptionalerKommentar",
    "title": "Uebersetzter Key"
  }
}
```
Den Link zum untergliederten Layer brauchen wir bei einer vollständigen Baumgenerierung nicht mehr.

**Comment by sheepyhollow** [comment]
Bei 2. ist aber noch zu klären, wo diese Metadaten herkommen 
(siehe https://github.com/GeoMatDigital/web-geomat/issues/16)

**Comment by mkay-sh** [comment]
Das stimmt. Eventuell mit einer seperaten Tabelle die den Kategoriekey auf Thumbnail und Kommentar mappt?

**Comment by chgad** [comment]
Nach der heutigen Besprechung obsolet. Neues Feaure wie in #299 .

Issue kann geschlossen werden.
