### ISSUE TITLE
Rework Photograph Model

### ISSUE THREAD

**Issue by chgad** [GeoMatDigital/django-geomat#301]
Es werden einige Änderungen am `Photograph` Model durchgeführt.

TODO:

- [x]  `orientation` ist obsolet, Relikt aus erstem Konzept, wird entfernt

- [x]  `shot_type` ist obsolet, Relikt aus erstem Konzept, wird entfernt

- [x]  `orig_height` Höhe des Orignal Bildes soll als `IntField` implementiert werden

- [x] `orig_width` Breite des Orignal Bildes soll als `IntField` implementiert werden

- [x] `description` Beschreibung des Bildes soll als `TextFeld` implementiert werden

- [x] `audio_file` Audio Files sollen hinzuzufügen sein.

Zu den existierenden Bildern soll in Zukunft ein genäherter Maßstab angezeigt werden.
Dazu wird ein Skalierungsfaktor händisch berechnet/abgelesen welcher anschließend für jedes Bild gespeichert werden soll.

- [x] zum `Photograph` Model ein neues `FloatField` hinzufügen `scale_factor`

**Comment by sheepyhollow** [comment]
Zwei Änderungen sind noch erbeten:
- Abspiellänge des Audiofiles (z.B. `audio_length` oder `audio_duration`)
- ein `TextFeld` für die Overlays, das SVG (und sonstigen) Code enthalten wird (z.B. `overlay`)

**Comment by sheepyhollow** [comment]
Das kann man eigentlich schließen oder?

**Comment by chgad** [comment]
Korrekt.
